# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

$modules_path = 'Modules/'

target 'CustomViewExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CustomViewExample
  pod 'DocumentDetector', :path => $modules_path + 'DocumentDetector'
  pod 'PassiveFaceLiveness', :path => $modules_path + 'PassiveFaceLiveness'
  pod 'FaceAuthenticator', :path => $modules_path + 'FaceAuthenticator'

  target 'CustomViewExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CustomViewExampleUITests' do
    # Pods for testing
  end

end
