# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'CustomViewExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CustomViewExample
  pod 'DocumentDetector', '~> 4.5.0'
  pod 'PassiveFaceLiveness', '~> 3.4.0'

  target 'CustomViewExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CustomViewExampleUITests' do
    # Pods for testing
  end

end

source 'https://github.com/combateafraude/iOS.git'
source 'https://cdn.cocoapods.org/' # ou 'https://github.com/CocoaPods/Specs' se o CDN estiver fora do ar
